### ISSUE TITLE
ModuleNotFoundError: No module named 'skimage'

### ISSUE THREAD

**Issue by wedgeewoo** [yoyo-nb/Thin-Plate-Spline-Motion-Model#37]
`A:\Thin-Plate-Spline-Motion-Model>set CUDA_VISIBLE_DEVICES=0 & python run.py --config config/vox-256.yaml --checkpoint checkpoints/vox.pth.tar --source_image assets/source.png --driving_video assets/driving.mp4 --find_best_frame --result_video SD_Avatar_Video.mp4
Traceback (most recent call last):
  File "A:\Thin-Plate-Spline-Motion-Model\run.py", line 9, in <module>
    from frames_dataset import FramesDataset
  File "A:\Thin-Plate-Spline-Motion-Model\frames_dataset.py", line 2, in <module>
    from skimage import io, img_as_float32
ModuleNotFoundError: No module named 'skimage'
`

**Comment by yoyo-nb** [comment]
`pip install scikit-image`

**Comment by wedgeewoo** [comment]
Do i install this in the /modules or in the main directory

**Comment by yoyo-nb** [comment]
It doesn't matter, `pip install` or `conda install` is global

**Comment by wedgeewoo** [comment]
now im getting this
  File "A:\Thin-Plate-Spline-Motion-Model\logger.py", line 7, in <module>
    from skimage.draw import circle
ImportError: cannot import name 'circle' from 'skimage.draw' (C:\Users\Buddy\AppData\Local\Programs\Python\Python310\lib\site-packages\skimage\draw\__init__.py).

**Comment by yoyo-nb** [comment]
Maybe we are using different versions, you can try this
`pip install -U scikit-image==0.18.3`

**Comment by wedgeewoo** [comment]
AssertionError: Torch not compiled with CUDA enabled

BTW im using Python 3.10 and not 3.9. would this cause an issue?

**Comment by yoyo-nb** [comment]
you installed the cpu version of torch, 
you can follow the instructions on [pytorch.org](https://pytorch.org/get-started/locally/) to install the appropriate version of torch

or you can run the code with cpu mode
```
python demo.py --config config/vox-256.yaml --checkpoint checkpoints/vox.pth.tar --source_image assets/source.png --driving_video assets/driving.mp4 --mode relative --find_best_frame --result_video SD_Avatar_Video.mp4 --cpu
```

**Comment by wedgeewoo** [comment]
i did cpu mode after trying to get gpu to work. I was able to get the cpu mode working after installing face alignment (pip install face-alignment==1.1.1), used your commands and i was able to render a video! Thanks for the help

**Comment by wedgeewoo** [comment]
I missing something about the gpu version of pytorch, im sure i followed the instructions correctly but I'm still unable to use the GPU. Still though thanks for the awesome repo
