### ISSUE TITLE
Error when training on my dataset

### ISSUE THREAD

**Issue by kinkan59** [yoyo-nb/Thin-Plate-Spline-Motion-Model#46]
(T-P-S-M-M) C:\Users\k\Desktop\T-P-S-M-M>python run.py --config config/vox-256.yaml
C:\Users\k\Desktop\T-P-S-M-M\run.py:38: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
None
Use predefined train-test split.
Training...
C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG19_Weights.IMAGENET1K_V1`. You can also use `weights=VGG19_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
  0%|                                                                                          | 0/100 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\k\Desktop\T-P-S-M-M\run.py", line 83, in <module>
    train(config, inpainting, kp_detector, bg_predictor, dense_motion_network, opt.checkpoint, log_dir, dataset)
  File "C:\Users\k\Desktop\T-P-S-M-M\train.py", line 55, in train
    for x in dataloader:
  File "C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\anaconda3\envs\T-P-S-M-M\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\k\Desktop\T-P-S-M-M\frames_dataset.py", line 172, in __getitem__
    return self.dataset[idx % self.dataset.__len__()]
  File "C:\Users\k\Desktop\T-P-S-M-M\frames_dataset.py", line 109, in __getitem__
    path = np.random.choice(glob.glob(os.path.join(self.root_dir, name + '*.mp4')))
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

please tell me what to do

**Comment by kinkan59** [comment]
Windows 10, anaconda environment
The one I'm trying now is the vox type
I can't download from YouTube well, so I'm doing it with the original video
id_sampling of vox-256.yaml was still True, so when I changed it to False, ValueError: 'a' cannot be empty unless no samples are taken no longer appears
Then RuntimeError: imageio.mimread() has read over 256000000B of image data.
Stopped to avoid memory problems. I got an error saying Use imageio.get_reader(), increase threshold, or memtest=False
The error no longer occurs when only videos with a size of 256 * 256 and a number of frames of 1000 or less are placed in the test or train folders.
Then RuntimeError: CUDA out of memory. Tried to allocate 224.00 MiB (GPU 0; 12.00 GiB total capacity; 10.69 GiB already allocated; 0 bytes free; 11.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Logs are recorded in the log folder, but there are empty train-vis, log.txt and vox-256.yaml with nothing written
I tried lowering the batch_size from 28 to 24, 20, 16, ... and the error disappeared at 8
I get NameError: name 'circle' is not defined
In the log folder, empty train-vis and vox-256.yaml are the same, but 00000000-checkpoint.pth is created
log.txt says 00000000) perceptual - 210.28008; equivariance_value - 0.65565; warp_loss - 7.71640 but no bg
Only 00000000 and nothing beyond 00000001
I don't know what happened from here
GPU memory is 12GB
Does batch_size: 8 make no sense?
Would increasing the number of something in the vox-256 file instead have the same effect?
I don't know how to solve the error NameError: name 'circle' is not defined
please professor
