### ISSUE TITLE
EOFError Ran out of input

### ISSUE THREAD

**Issue by themichaelminer** [yoyo-nb/Thin-Plate-Spline-Motion-Model#79]
![Screen Shot 2023-07-07 at 11 38 44 AM](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/assets/128749675/702d7ec3-54be-42ec-9f3f-2d66b3f8005f)
![Screen Shot 2023-07-07 at 11 38 21 AM](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/assets/128749675/f0e8840f-8105-4524-a2e8-70897133bf90)

**Comment by abhijatchaturvedi** [comment]
Can you try with 
`!pip install face-alignment==1.3.4`

**Comment by themichaelminer** [comment]
It's saying this after changing the code to that

![Screen Shot 2023-07-07 at 1 37 33 PM](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/assets/128749675/4a75fe51-a8ec-496c-bd23-e0dfecadd15b)

**Comment by yoyo-nb** [comment]
This error may be due to not downloading the correct model. Previously, I had stored the model on Tsinghua Cloud, but since I have graduated from Tsinghua University, I cannot continue to use it, and the model was deleted. However, I have now uploaded the model to Yandex and it can be downloaded using the following commands:
```
!mkdir checkpoints
!pip3 install wldhx.yadisk-direct
!curl -L $(yadisk-direct https://disk.yandex.com/d/i08z-kCuDGLuYA) -o checkpoints/vox.pth.tar
```
![image](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/assets/48593306/01bfab48-546d-44e3-b31d-19b746731d1f)

**Comment by themichaelminer** [comment]
that fixed it! awesome!

**Comment by allthingssecurity** [comment]
unable to download 
Traceback (most recent call last):
  File "/usr/local/bin/yadisk-direct", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/wldhx/yadisk_direct/main.py", line 23, in main
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/usr/local/lib/python3.10/dist-packages/wldhx/yadisk_direct/main.py", line 23, in <listcomp>
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/usr/local/lib/python3.10/dist-packages/wldhx/yadisk_direct/main.py", line 12, in get_real_direct_link
    return pk_request.json()['href']
KeyError: 'href'

**Comment by sarique2003** [comment]
!mkdir checkpoints
!wget -c https://cloud.tsinghua.edu.cn/f/da8d61d012014b12a9e4/?dl=1 -O checkpoints/vox.pth.tar

Chnage it to this and shoudl work that is a curl error.

**Comment by sarique2003** [comment]
!mkdir checkpoints
!wget -c https://cloud.tsinghua.edu.cn/f/da8d61d012014b12a9e4/?dl=1 -O checkpoints/vox.pth.tar

Change it to this it should work .

**Comment by lokesh005** [comment]
I am still getting same error as @themichaelminer, 

When I performed what @sarique2003 mentioned I am below getting error, though file is getting created
<img width="1101" alt="Screenshot 2023-07-12 at 8 05 19 PM" src="https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/assets/11570450/c84baa62-a88b-47c9-89bd-d0fa67ebc81f">

Even after performing what @yoyo-nb suggested I am getting the same error as @allthingssecurity is getting.

Can anyone please help here.

**Comment by sarique2003** [comment]
My bad it has been removed from tsinghua cloud, intially i followed what @yoyo-nb said and it worked , now i am facing the same error again.

**Comment by yoyo-nb** [comment]
@sarique2003 @allthingssecurity @lokesh005 
Sorry, this is because Yandex is displaying the message "Download limit exceeded".  

According to the Yandex Disk [website](https://yandex.com/support/disk/actions-files/troubleshooting.html): 
>If a public file was downloaded many times during the day, the download limit is activated, and the download may be restricted for a day. If you don't want to wait, save the file to your Yandex Disk using the Save to Yandex Disk button.

You can try manually downloading the model from [Yandex](https://disk.yandex.com/d/bWopgbGj1ZUV1w) or [Google Drive](https://drive.google.com/drive/folders/1pNDo1ODQIb5HVObRtCmubqJikmR7VVLT?usp=sharing), and then upload it to the corresponding location in Google Colab.
![image](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/assets/48593306/2ba47804-c89a-435c-8305-b54cf0429ed0)

**Comment by AIdud4212** [comment]
![2023-08-15_17-06-08](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/assets/138531171/957a358b-68fa-4e18-b89d-67864f066499)
I registered links to the models (the author fixed them in the code), manually uploaded all the models to the Checkpoints folder.
But it still gives an error .. What could be?

**Comment by sarique2003** [comment]
thanks @yoyo-nb it worked
