### ISSUE TITLE
I have a problem with curling

### ISSUE THREAD

**Issue by MaxaAI** [yoyo-nb/Thin-Plate-Spline-Motion-Model#94]
When i run the 3rd cell i get this error

Traceback (most recent call last):
  File "/usr/local/bin/yadisk-direct", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/wldhx/yadisk_direct/main.py", line 23, in main
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/usr/local/lib/python3.10/dist-packages/wldhx/yadisk_direct/main.py", line 23, in <listcomp>
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/usr/local/lib/python3.10/dist-packages/wldhx/yadisk_direct/main.py", line 12, in get_real_direct_link
    return pk_request.json()['href']
KeyError: 'href'
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

How am i able to fix it?

**Comment by ashish-gupta-99** [comment]
I think we should download models using `wget`  from github release, instead of curling from 3rd party site: 
https://disk.yandex.com
you can directly download models from above site, by pating curl url in browser.
